version: "3.8"

services:
  # Frontend (tu aplicación Next.js)
  frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - api
      - panel

  # Backend API (asume que tienes un Dockerfile en ../api o ajusta la ruta)
  api:
    build: ../api # Cambia esta ruta si el backend API está en otro lugar
    ports:
      - "4000:4000" # Ajusta el puerto según tu API
    environment:
      - NODE_ENV=development
    volumes:
      - ../api:/app # Monta el código para desarrollo
      - /app/node_modules

  # Backend Panel (asume que tienes un Dockerfile en ../panel o ajusta la ruta)
  panel:
    build: ../panel # Cambia esta ruta si el backend panel está en otro lugar
    ports:
      - "5000:5000" # Ajusta el puerto según tu panel
    environment:
      - NODE_ENV=development
    volumes:
      - ../panel:/app # Monta el código para desarrollo
      - /app/node_modules

networks:
  default:
    driver: bridge
